### PR TITLE
table & functions

### PR DESCRIPTION
**Pull request by news-papers**
I did tables and functions

Couldn't finish it completely, but the table is created:
<html>
<body>
<h3 style="color: rgb(0, 0, 0); font-family: Times, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 239); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Link Table</h3>

Preceded By | Succeeded By | Related Links
-- | -- | --
cat | 1654

</body>
</html>

### CODE REVIEW

**Review by nznewspapers — APPROVED** [review]
Looking good so far. Do you want to merge yet?

**Comment by news-papers** [comment]
There's a bug? Why? @nznewspapers

**Comment by news-papers** [comment]
There's conflicts and I just wanted to make sure you were aware of that

**Comment by news-papers** [comment]
Because I don't know which code to keep

**Pull request merged**
